/**
 * connect.mjs — render DeanGo's connection files from a DetectionReport and
 * (optionally) merge them into the detected setups.
 *
 * Output root: $DEANGO_HOME (default ~/.deango)
 *   bin/hermes-acp-launcher.sh        the spawned brain (stdio-pure wrapper)
 *   openclaw/acpx.hermes.config.json  acpx snippet (agents.hermes + MCP bridges)
 *   hermes/cli-config.deango.yaml     brain-side managed block
 *   connection/units.json             supervisor units (gateway + brain probe)
 *   connection/manifest.json          what DeanGo wrote, where, and why
 *
 * `apply: true` additionally merges the acpx snippet into the detected OpenClaw
 * JSON config (deep merge, timestamped backup) and upserts a managed block into
 * the detected Hermes cli-config.yaml. Dry-run by default.
 */
import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { DEANGO_HOME, deepMerge, readJson, writeJson, upsertManagedBlock, isFile } from "./util.mjs";

export const TEMPLATES = {
  launcher: (opts) => `#!/usr/bin/env bash
# Generated by DeanGo. Spawns the Hermes brain for OpenClaw's acpx runtime.
# stdout is protocol-only (ACP JSON-RPC). Diagnostics → stderr.
set -euo pipefail
log() { printf '[deango/hermes-acp] %s\\n' "$*" >&2; }
HERMES_HOME="\${HERMES_HOME:-${opts.hermesHome || "$HOME/.hermes"}}"
export HERMES_HOME PYTHONUNBUFFERED=1 PYTHONIOENCODING=utf-8 TERM=dumb NO_COLOR=1
${opts.hermesCheckout ? `export PYTHONPATH="${opts.hermesCheckout}\${PYTHONPATH:+:\$PYTHONPATH}"
LAUNCH=( python -m acp_adapter )` : `LAUNCH=( ${opts.hermesBin || "hermes-acp"} )`}
log "exec: \${LAUNCH[*]}"
exec "\${LAUNCH[@]}"
`,

  acpx: (opts) => ({
    agents: {
      hermes: { command: opts.launcherPath, args: [], env: { HERMES_HOME: opts.hermesHome || "~/.hermes" } },
    },
    probeAgent: "hermes",
    permissionMode: "approve-reads",
    nonInteractivePermissions: "deny",
    openClawToolsMcpBridge: true,
    pluginToolsMcpBridge: true,
    timeoutSeconds: 120,
    nativeAgents: { opencode: false, qwen: false, pi: false, kilocode: false, copilot: false },
  }),

  hermesConfig: () => `# Managed by DeanGo — brain-side settings for the bridged organism.
# Cognition stays on; world-contact flows through OpenClaw hands (MCP bridges).
memory: { enabled: true }
skills: { auto_improve: true }
session_search: { enabled: true }
approval_mode: smart
quiet_mode: true
`,

  units: (opts) => ({
    units: [
      {
        id: "openclaw-gateway",
        label: "OpenClaw Gateway (nerves+limbs)",
        cmd: opts.openclawBin || "openclaw",
        args: ["gateway", "start"],
        autostart: true,
        healthProbe: { type: "cli", args: ["gateway", "status"] },
      },
      {
        id: "hermes-acp",
        label: "Hermes brain (standalone ACP probe)",
        cmd: opts.launcherPath,
        args: [],
        autostart: false,
        note: "Normally spawned by OpenClaw acpx per session; start manually only for probing.",
      },
    ],
  }),
};

/** Plan the connection: pure render, no writes. */
export function planConnection(det) {
  const h = det.hermes, o = det.openclaw;
  const launcherPath = path.join(DEANGO_HOME, "bin", "hermes-acp-launcher.sh");
  const opts = {
    launcherPath,
    hermesHome: h.home || undefined,
    hermesCheckout: h.checkout || undefined,
    hermesBin: h.bins?.find((b) => b.name === "hermes-acp")?.path || h.bins?.[0]?.path,
    openclawBin: o.bins?.[0]?.path,
  };
  return {
    deangoHome: DEANGO_HOME,
    files: [
      { path: launcherPath, kind: "script", content: TEMPLATES.launcher(opts), mode: 0o755 },
      { path: path.join(DEANGO_HOME, "openclaw", "acpx.hermes.config.json"), kind: "openclaw-snippet", content: JSON.stringify(TEMPLATES.acpx(opts), null, 2) + "\n" },
      { path: path.join(DEANGO_HOME, "hermes", "cli-config.deango.yaml"), kind: "hermes-snippet", content: TEMPLATES.hermesConfig() },
      { path: path.join(DEANGO_HOME, "connection", "units.json"), kind: "units", content: JSON.stringify(TEMPLATES.units(opts), null, 2) + "\n" },
    ],
    mergeTargets: {
      openclawConfig: o.configFiles?.find((f) => f.endsWith(".json")) || null,
      hermesConfig: h.configFiles?.find((f) => f.endsWith(".yaml")) || null,
    },
    warnings: [
      ...(o.installed ? [] : ["openclaw not detected — run `deango setup` after installing, or use the setup planner."]),
      ...(h.installed ? [] : ["hermes not detected — run `deango setup` after installing, or use the setup planner."]),
      ...(o.configFiles?.length ? [] : ["no openclaw config file found; snippet written for manual merge."]),
    ],
  };
}

/** Write the connection files (and optionally merge into live configs). */
export async function buildConnection(det, { apply = false } = {}) {
  const plan = planConnection(det);
  const written = [];
  for (const f of plan.files) {
    await fsp.mkdir(path.dirname(f.path), { recursive: true });
    await fsp.writeFile(f.path, f.content);
    if (f.mode) await fsp.chmod(f.path, f.mode);
    written.push({ path: f.path, bytes: Buffer.byteLength(f.content) });
  }

  const merges = [];
  if (apply && plan.mergeTargets.openclawConfig) {
    const target = plan.mergeTargets.openclawConfig;
    const current = (await readJson(target)) || {};
    const snippet = JSON.parse(plan.files[1].content);
    const merged = deepMerge(current, { plugins: { acpx: snippet } });
    const backup = `${target}.deango-backup-${Date.now()}.json`;
    await fsp.copyFile(target, backup);
    await writeJson(target, merged);
    merges.push({ target, backup, strategy: "json deep-merge → plugins.acpx" });
  }
  if (apply && plan.mergeTargets.hermesConfig) {
    const target = plan.mergeTargets.hermesConfig;
    const current = await fsp.readFile(target, "utf8").catch(() => "");
    const next = upsertManagedBlock(current, "connection", plan.files[2].content);
    const backup = `${target}.deango-backup-${Date.now()}.yaml`;
    if (isFile(target)) await fsp.copyFile(target, backup);
    await fsp.writeFile(target, next);
    merges.push({ target, backup, strategy: "managed-block upsert" });
  }

  const manifest = {
    builtAt: new Date().toISOString(), apply, written, merges,
    detectionSnapshot: { hermes: plan.warnings.length ? det.hermes.installed : true, openclaw: det.openclaw.installed },
  };
  await writeJson(path.join(DEANGO_HOME, "connection", "manifest.json"), manifest);
  return { plan, written, merges };
}
