// Package connect — render DeanGo's connection files and optionally merge
// them into the detected live configs (timestamped backups first).
package connect

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"deango/internal/model"
	"deango/internal/util"
)

type opts struct {
	launcherPath  string
	hermesHome    string
	hermesCheckout string
	hermesBin     string
	openclawBin   string
}

func gather(det model.DetectionReport) opts {
	o := opts{launcherPath: filepath.Join(util.DeangoHome(), "bin", "hermes-acp-launcher.sh")}
	o.hermesHome = det.Hermes.Home
	o.hermesCheckout = det.Hermes.Checkout
	for _, b := range det.Hermes.Bins {
		if b.Name == "hermes-acp" && o.hermesBin == "" {
			o.hermesBin = b.Path
		}
	}
	if o.hermesBin == "" && len(det.Hermes.Bins) > 0 {
		o.hermesBin = det.Hermes.Bins[0].Path
	}
	if len(det.Openclaw.Bins) > 0 {
		o.openclawBin = det.Openclaw.Bins[0].Path
	}
	return o
}

func launcherTmpl(o opts) string {
	home := o.hermesHome
	if home == "" {
		home = "$HOME/.hermes"
	}
	var launch string
	if o.hermesCheckout != "" {
		launch = fmt.Sprintf("export PYTHONPATH=%q\nLAUNCH=( python -m acp_adapter )", o.hermesCheckout+"${PYTHONPATH:+:$PYTHONPATH}")
	} else {
		bin := o.hermesBin
		if bin == "" {
			bin = "hermes-acp"
		}
		launch = "LAUNCH=( " + bin + " )"
	}
	return `#!/usr/bin/env bash
# Generated by DeanGo (Go core). Spawns the Hermes brain for OpenClaw's acpx runtime.
# stdout is protocol-only (ACP JSON-RPC). Diagnostics -> stderr.
set -euo pipefail
log() { printf '[deango/hermes-acp] %s\n' "$*" >&2; }
HERMES_HOME="${HERMES_HOME:-` + home + `}"
export HERMES_HOME PYTHONUNBUFFERED=1 PYTHONIOENCODING=utf-8 TERM=dumb NO_COLOR=1
` + launch + `
log "exec: ${LAUNCH[*]}"
exec "${LAUNCH[@]}"
`
}

func acpxSnippet(o opts) map[string]any {
	home := o.hermesHome
	if home == "" {
		home = "~/.hermes"
	}
	return map[string]any{
		"agents": map[string]any{
			"hermes": map[string]any{
				"command": o.launcherPath,
				"args":    []string{},
				"env":     map[string]string{"HERMES_HOME": home},
			},
		},
		"probeAgent":              "hermes",
		"permissionMode":          "approve-reads",
		"nonInteractivePermissions": "deny",
		"openClawToolsMcpBridge":  true,
		"pluginToolsMcpBridge":    true,
		"timeoutSeconds":          120,
		"nativeAgents": map[string]any{
			"opencode": false, "qwen": false, "pi": false, "kilocode": false, "copilot": false,
		},
	}
}

func hermesConfigTmpl() string {
	return `# Managed by DeanGo — brain-side settings for the bridged organism.
# Cognition stays on; world-contact flows through OpenClaw hands (MCP bridges).
memory: { enabled: true }
skills: { auto_improve: true }
session_search: { enabled: true }
approval_mode: smart
quiet_mode: true
`
}

func unitsJSON(o opts) model.UnitsFile {
	cmd := o.openclawBin
	if cmd == "" {
		cmd = "openclaw"
	}
	return model.UnitsFile{Units: []model.Unit{
		{
			ID: "openclaw-gateway", Label: "OpenClaw Gateway (nerves+limbs)",
			Cmd: cmd, Args: []string{"gateway", "start"}, Autostart: true,
			HealthProbe: &model.HealthProbe{Type: "cli", Args: []string{"gateway", "status"}},
		},
		{
			ID: "hermes-acp", Label: "Hermes brain (standalone ACP probe)",
			Cmd: o.launcherPath, Args: []string{}, Autostart: false,
			Note: "Normally spawned by OpenClaw acpx per session; start manually only for probing.",
		},
	}}
}

func mustJSON(v any) string {
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return `{"error":"template encode failed"}`
	}
	return string(raw) + "\n"
}

// PlanConnection renders everything without touching disk beyond reads.
func PlanConnection(det model.DetectionReport) model.ConnectionPlan {
	o := gather(det)
	warnings := []string{}
	if !det.Openclaw.Installed {
		warnings = append(warnings, "openclaw not detected — run `deango setup` after installing, or use the setup planner.")
	}
	if !det.Hermes.Installed {
		warnings = append(warnings, "hermes not detected — run `deango setup` after installing, or use the setup planner.")
	}
	mt := model.MergeTargets{}
	for _, f := range det.Openclaw.ConfigFiles {
		if strings.HasSuffix(f, ".json") {
			mt.OpenclawConfig = f
			break
		}
	}
	for _, f := range det.Hermes.ConfigFiles {
		if strings.HasSuffix(f, ".yaml") {
			mt.HermesConfig = f
			break
		}
	}
	if len(det.Openclaw.ConfigFiles) == 0 {
		warnings = append(warnings, "no openclaw config file found; snippet written for manual merge.")
	}
	return model.ConnectionPlan{
		DeangoHome: util.DeangoHome(),
		Files: []model.PlanFile{
			{Path: o.launcherPath, Kind: "script", Content: launcherTmpl(o), Mode: 0o755},
			{Path: filepath.Join(util.DeangoHome(), "openclaw", "acpx.hermes.config.json"), Kind: "openclaw-snippet", Content: mustJSON(acpxSnippet(o))},
			{Path: filepath.Join(util.DeangoHome(), "hermes", "cli-config.deango.yaml"), Kind: "hermes-snippet", Content: hermesConfigTmpl()},
			{Path: filepath.Join(util.DeangoHome(), "connection", "units.json"), Kind: "units", Content: mustJSON(unitsJSON(o))},
		},
		MergeTargets: mt,
		Warnings:     warnings,
	}
}

// BuildConnection writes all plan files; apply=true additionally merges into
// the detected live configs (timestamped backups first).
func BuildConnection(det model.DetectionReport, apply bool) (model.BuildResult, error) {
	plan := PlanConnection(det)
	res := model.BuildResult{Plan: plan, Written: []model.WrittenFile{}, Merges: []model.MergeRecord{}}
	for _, f := range plan.Files {
		if err := os.MkdirAll(filepath.Dir(f.Path), 0o755); err != nil {
			return res, err
		}
		if err := os.WriteFile(f.Path, []byte(f.Content), 0o644); err != nil {
			return res, err
		}
		if f.Mode != 0 {
			_ = os.Chmod(f.Path, os.FileMode(f.Mode))
		}
		res.Written = append(res.Written, model.WrittenFile{Path: f.Path, Bytes: len(f.Content)})
	}

	if apply && plan.MergeTargets.OpenclawConfig != "" {
		target := plan.MergeTargets.OpenclawConfig
		current, err := util.ReadJSONFile(target)
		if err != nil {
			current = map[string]any{}
		}
		var snippet map[string]any
		if err := json.Unmarshal([]byte(plan.Files[1].Content), &snippet); err != nil {
			return res, fmt.Errorf("acpx snippet decode: %w", err)
		}
		merged := util.DeepMerge(current, map[string]any{"plugins": map[string]any{"acpx": snippet}})
		backup := fmt.Sprintf("%s.deango-backup-%d.json", target, time.Now().Unix())
		if util.IsFile(target) {
			raw, _ := os.ReadFile(target)
			if err := os.WriteFile(backup, raw, 0o644); err != nil {
				return res, err
			}
		}
		if err := util.WriteJSONFile(target, merged); err != nil {
			return res, err
		}
		res.Merges = append(res.Merges, model.MergeRecord{Target: target, Backup: backup, Strategy: "json deep-merge → plugins.acpx"})
	}

	if apply && plan.MergeTargets.HermesConfig != "" {
		target := plan.MergeTargets.HermesConfig
		raw, _ := os.ReadFile(target)
		next := util.UpsertManagedBlock(string(raw), "connection", plan.Files[2].Content)
		backup := fmt.Sprintf("%s.deango-backup-%d.yaml", target, time.Now().Unix())
		if util.IsFile(target) {
			if err := os.WriteFile(backup, raw, 0o644); err != nil {
				return res, err
			}
		}
		if err := os.WriteFile(target, []byte(next), 0o644); err != nil {
			return res, err
		}
		res.Merges = append(res.Merges, model.MergeRecord{Target: target, Backup: backup, Strategy: "managed-block upsert"})
	}

	manifest := map[string]any{
		"builtAt":  time.Now().UTC().Format(time.RFC3339),
		"apply":    apply,
		"written":  res.Written,
		"merges":   res.Merges,
		"core":     "go",
	}
	if err := util.WriteJSONFile(filepath.Join(util.DeangoHome(), "connection", "manifest.json"), manifest); err != nil {
		return res, err
	}
	return res, nil
}
